SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE       VIEW [AwmConfig].[vMapping] AS
WITH Macchine AS
(
    SELECT	C.ID_SOTTOAREA, c.ID_COMPONENTE, sc.ID_SOTTOCOMPONENTE, P.ID_PARTIZIONE, p.DESCRIZIONE
    FROM	dbo.Componenti C
    LEFT 
	JOIN	dbo.SottoComponenti SC 
	ON		c.ID_COMPONENTE = sc.ID_COMPONENTE
    LEFT 
	JOIN	dbo.Partizioni P 
	ON SC.ID_SOTTOCOMPONENTE = p.ID_SOTTOCOMPONENTE
    WHERE C.ID_TIPO_COMPONENTE IN ('T','C') OR C.Tipo = 'Supercap'
)

SELECT	m.ID_PARTIZIONE AS Id_Macchina,
		m.DESCRIZIONE AS Macchina,
		CO.ID_COMPONENTE AS Id_Scaffale,
		CO.DESCRIZIONE AS Scaffale

FROM	dbo.Componenti CO
JOIN	Macchine m 
ON		CO.ID_COMPONENTE <> m.ID_COMPONENTE


WHERE	CO.ID_TIPO_COMPONENTE = 'S'
    AND CO.ID_SOTTOAREA = m.ID_SOTTOAREA
	AND RIGHT(m.DESCRIZIONE,1) = '1' -- nel caso la macchina abbia piu partizioni da mappare togli 
GO
