SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [AwmConfig].[vPiani] AS
SELECT DISTINCT TOP 100 PERCENT				A.ID_AREA, 
											C.ID_COMPONENTE,
											A.DESCRIZIONE, 
											ISNULL(SC.PIANO,0) PIANO
FROM	SottoComponenti SC
JOIN	Componenti		C
ON		C.ID_COMPONENTE = SC.ID_COMPONENTE
JOIN	SottoAree		SA
ON		SA.ID_SOTTOAREA = C.ID_SOTTOAREA 
JOIN	Aree			A
ON		A.ID_AREA  = SA.ID_AREA
WHERE	ISNULL(PIANO,0) <> 0 
		AND ID_TIPO_COMPONENTE = 'S'
ORDER BY PIANO ASC

GO
