SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [AwmConfig].[vUscite]
AS

SELECT	ID_PARTIZIONE					Value,
		SUBSTRING( DESCRIZIONE,1,4)		Description
FROM	dbo.Partizioni
WHERE	ID_TIPO_PARTIZIONE = 'US' --VALORE UTILIZZATO SOLO COME FILTRO IN VISUALIZZAZION
GO
