SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[vKPI_Magazzino]  AS 


              SELECT  COMP.ID_COMPONENTE, COMP.DESCRIZIONE, TC.DESCRIZIONE AS COMP_TIPO_DESC, COMP.ID_TIPO_COMPONENTE, SOTTO.ID_SOTTOCOMPONENTE, SOTTO.DESCRIZIONE AS SOTTO_COMP_DESC,
			          AD.Id_Partizione_Sorgente, PTS.DESCRIZIONE AS PART_SORGENTE, AD.Id_Partizione_Destinazione, PTD.DESCRIZIONE AS PART_DESTINAZIONE,
			          ATEMP.Id_Tempo , ATEMP.Millisecondi , Convert(varchar, ATEMP.Timestamp,103) as Data_Exec
			  FROM    Componenti COMP JOIN SottoComponenti SOTTO
				      ON  COMP.ID_COMPONENTE = SOTTO.ID_COMPONENTE
					  JOIN Partizioni PTS ON SOTTO.ID_SOTTOCOMPONENTE = PTS.ID_SOTTOCOMPONENTE
					  JOIN Adiacenze AD ON AD.Id_Partizione_Sorgente = PTS.ID_PARTIZIONE
					  JOIN Partizioni PTD ON AD.Id_Partizione_Destinazione = PTD.ID_PARTIZIONE
					  JOIN Tipo_Componenti TC ON COMP.ID_TIPO_COMPONENTE = TC.ID_TIPO_COMPONENTE
					  JOIN Adiacenze_Tempi ATEMP ON ATEMP.Id_Adiacenza = AD.Id_Adiacenza
					  WHERE COMP.ID_TIPO_COMPONENTE != 'S'



GO
