SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE VIEW [Graph].[IdentityServiceLogs]
AS
SELECT	CONVERT(SMALLDATETIME, TimeStamp) AS XAxis, LogLevel AS Labels,COUNT(1) AS YAxis 
FROM	Logs.IdentityServiceLogs
--WHERE CONVERT(SMALLDATETIME, TimeStamp) BETWEEN '2021-07-12 00:01:00' AND '2021-07-12 10:45:00'
GROUP BY
CONVERT	(SMALLDATETIME, TimeStamp),LogLevel
GO
