SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [Scada].[vPiani] AS
SELECT	TOP (100)
		SA.ID_SOTTOAREA,
		C.ID_COMPONENTE,
		SA.DESCRIZIONE,
		ISNULL(PIANO,0)	PIANO
FROM	Partizioni			P
JOIN	SottoComponenti		SC
ON		SC.ID_SOTTOCOMPONENTE = P.ID_SOTTOCOMPONENTE
	AND ISNULL(PIANO,0) <> 0
JOIN	Componenti			C
ON		C.ID_COMPONENTE = SC.ID_COMPONENTE
JOIN	SottoAree			SA
ON		SA.ID_SOTTOAREA = C.ID_SOTTOAREA
GROUP BY SA.ID_SOTTOAREA,
		C.ID_COMPONENTE,
		SA.DESCRIZIONE,
		ISNULL(PIANO,0)
		ORDER BY ISNULL(PIANO,0)
GO
