SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[sp_CreazioneScaffale]
	@ID_Area INT,
	@PIANI INT,
	@COLONNE INT,
	@ALTEZZA INT,
	@LARGHEZZA INT,
	@PROFONDITA INT,
	@PESO INT,
	@CAPIENZA INT
AS
BEGIN
	BEGIN TRANSACTION;
	BEGIN TRY	
		 -- Dichiarazioni Variabili;
		DECLARE @CA_AREA CHAR(1)
		DECLARE @CA_SOTTOAREA CHAR(1)
		DECLARE @CA_COMPONENTE CHAR(2)

		DECLARE @PIANO INT
		DECLARE @COLONNA INT
		DECLARE @ID_SOTTOAREA INT
		DECLARE @ID_COMPONENTE INT
	
		WHILE ISNULL(@PIANO,0) < @PIANI
		BEGIN
			SET @PIANO = ISNULL(@PIANO,0) + 1
			SET @COLONNA = NULL
			SELECT @CA_AREA = CODICE_ABBREVIATO FROM dbo.Aree WHERE ID_AREA = @ID_Area
			
			IF @PIANO = 1 SET @CA_SOTTOAREA = 'A'
			IF @PIANO = 2 SET @CA_SOTTOAREA = 'B'
			IF @PIANO = 3 SET @CA_SOTTOAREA = 'C'
			IF @PIANO = 4 SET @CA_SOTTOAREA = 'D'
			IF @PIANO = 5 SET @CA_SOTTOAREA = 'E'
			IF @PIANO = 6 SET @CA_SOTTOAREA = 'F'
			
			-- CREO SOTTOAREA
			SET IDENTITY_INSERT dbo.SottoAree ON
			SET @ID_SOTTOAREA = CAST(@ID_Area AS VARCHAR(10)) + CAST(@PIANO AS CHAR(1))
			INSERT INTO dbo.SottoAree
			(
				ID_SOTTOAREA,
			    ID_AREA,
			    DESCRIZIONE,
			    CODICE_ABBREVIATO,
			    PickingEnable
			)
			VALUES(@ID_SOTTOAREA, @ID_Area, @CA_AREA + @CA_SOTTOAREA + '00' ,@CA_SOTTOAREA,0  )
            SET IDENTITY_INSERT dbo.SottoAree OFF
			
			WHILE ISNULL(@COLONNA,0) < @COLONNE
			BEGIN
				
				SET @COLONNA = ISNULL(@COLONNA,0) + 1

				PRINT @PIANO
				PRINT @COLONNA

				-- CREO IL COMPONENTE
				SET IDENTITY_INSERT dbo.Componenti ON
				SET @CA_COMPONENTE = REPLACE(STR(@COLONNA, 2), SPACE(1), '0')
				SET @ID_COMPONENTE = CAST(@ID_SOTTOAREA AS VARCHAR(10)) + @CA_COMPONENTE
				INSERT INTO dbo.Componenti
				(
					ID_COMPONENTE,
					ID_SOTTOAREA,
					DESCRIZIONE,
					CODICE_ABBREVIATO,
					ID_TIPO_COMPONENTE,
					COMM_CHANNEL,
					Tipo,
					Configurazione
				)
				VALUES
				(@ID_COMPONENTE, @ID_SOTTOAREA, @CA_AREA + @CA_SOTTOAREA + @CA_COMPONENTE, @CA_COMPONENTE, 'S', 1, NULL, NULL)
				SET IDENTITY_INSERT dbo.Componenti OFF

				-- CREO IL SOTTOCOMPONENTE
				SET IDENTITY_INSERT dbo.SottoComponenti ON
				INSERT INTO dbo.SottoComponenti
				(	
					ID_SOTTOCOMPONENTE,
				    ID_COMPONENTE,
				    DESCRIZIONE,
				    CODICE_ABBREVIATO,
				    COLONNA,
				    PIANO,
				    svgOFFSET
				)
				VALUES
				(   @ID_COMPONENTE, @ID_COMPONENTE, @CA_AREA + @CA_SOTTOAREA + @CA_COMPONENTE + '.0001','0001',@COLONNA,@PIANO,0)
				SET IDENTITY_INSERT dbo.SottoComponenti OFF

				SET IDENTITY_INSERT dbo.Partizioni ON
				INSERT INTO dbo.Partizioni (ID_PARTIZIONE, ID_SOTTOCOMPONENTE,DESCRIZIONE,CODICE_ABBREVIATO,ID_TIPO_PARTIZIONE,CAPIENZA,ALTEZZA,LARGHEZZA,PROFONDITA,PESO)
				VALUES
				(
					@ID_COMPONENTE,
					@ID_COMPONENTE,
					@CA_AREA + @CA_SOTTOAREA + @CA_COMPONENTE + '.0001.0001',
					'0001', 
					'MA', 
					@CAPIENZA, 
					@ALTEZZA,
					@LARGHEZZA,
					@PROFONDITA,
					@PESO
				)
				SET IDENTITY_INSERT dbo.Partizioni OFF

			END

		END
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION;
		THROW;
	END CATCH;
END;
GO
