CREATE TABLE [dbo].[TAG]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CHANNELID] [int] NOT NULL,
[SUBSCRIBE] [int] NULL,
[TAGID] [varchar] (500) COLLATE Latin1_General_CI_AS NOT NULL,
[TAGTYPE] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[DESCRIPTION] [varchar] (500) COLLATE Latin1_General_CI_AS NOT NULL,
[ASI] [varchar] (max) COLLATE Latin1_General_CI_AS NULL,
[TARGETID] [int] NULL,
[EXPECTEDTARGETVALUE] [bit] NULL,
[DB] [int] NULL,
[BYTE_DB] [int] NULL,
[BIT_DB] [int] NULL,
[NAME] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[TYPE] [varchar] (100) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAG] ADD CONSTRAINT [PK_TAG_s300] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_TAG] ON [dbo].[TAG] ([TAGID], [CHANNELID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
