CREATE TABLE [dbo].[SottoAree]
(
[ID_AREA] [int] NOT NULL,
[ID_SOTTOAREA] [int] NOT NULL IDENTITY(1, 1),
[DESCRIZIONE] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[CODICE_ABBREVIATO] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[PickingEnable] [bit] NOT NULL CONSTRAINT [DF__SottoAree__Picki__5CB79AF1] DEFAULT ((1)),
[COMPORTAMENTO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SottoAree] ADD CONSTRAINT [PK_SottoAree] PRIMARY KEY CLUSTERED ([ID_SOTTOAREA]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SottoAree_1] ON [dbo].[SottoAree] ([ID_AREA], [CODICE_ABBREVIATO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SottoAree] ADD CONSTRAINT [FK_SottoAree_Aree] FOREIGN KEY ([ID_AREA]) REFERENCES [dbo].[Aree] ([ID_AREA])
GO
